baseURL = 'https://sccotliu.github.io/'
#languageCode = 'zh-cn'
title = '心的博客'
theme = 'vno-hugo'


        

defaultContentLanguage = 'zh-cn'
[languages]
  [languages.en-us]
    languageName = 'English(United States)'
    weight = 10
  [languages.zh-cn]
    languageName = '简体中文（中国大陆）'
    weight = 20


# Pagination
paginate = 10
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "高考倒计时"
    identifier = "projects"
    url = "http://k-zone.xyz/game"
    weight = 10
 [[menu.main]]
    name = "Tags"
    identifier = "Tags"
    url = "/tags/"
    weight = 20
[taxonomies]
    tag = "tags"


[params]
author = "ScottLiu"
subtitle = "原来的[福荣园博客]已关闭，这里重新开始"
description = "随笔 + 照片"
welcomeMessage = "闲人一个"

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = "red"

[params.comment]
disqus = "vno-hugo"
duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
weibo = "onevcat"
github = "onevcat"
twitter = "onevcat"
gplus = "107108267983477358170"
mail = "liu198143@126.com"
linkedin = "example"

[params.ga]
ID = "your_ga_id"
host = "your_host"

# The blog button should not be removed.
[params.blogButton]
title = "Blog"
description = "Visit blog"

[params.copyright]
license = 'CC BY-NC-SA 4.0'
license_link = 'http://creativecommons.org/licenses/by-nc-sa/4.0/'

[permalinks]
posts = "/:year/:month/:title/"
